### ISSUE TITLE
Forking MySQL adapter would be easier

### ISSUE THREAD

**Issue by fahad19** [alexweber/firenze-adapter-sqlite#1]
Forking this repo, and making only a few changes would be easier IMO: https://github.com/fahad19/firenze-adapter-mysql

MySQL adapter already uses knex.js, which has support for sqlite and other sql-like database. just my two cents :)

**Comment by alexweber** [comment]
@fahad19 good call! although this will probably be a better learning experience for me :)

**Comment by fahad19** [comment]
@alexweber: coolio! kindly send a PR when ready for adding to this list: https://github.com/fahad19/firenze#available-adapters
